#pragma kernel CSMain

uint size;
float max_norm;
RWStructuredBuffer<float> buffer;

[numthreads(512, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float sum = 0.0;
    for (uint i = 0; i < size; i++)
    {
        sum += buffer[i] * buffer[i];
    }
    sum = sqrt(sum);
    if (sum <= max_norm) return;
    for (uint j = 0; j < size; j++)
    {
        buffer[j] = buffer[j] / sum;
    }
    
}